name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (release)
        run: swift build -c release

      - name: Package artifact
        run: |
          mkdir -p dist
          cp .build/release/xcq dist/
          cd dist
          zip -r xcq-${{ github.ref_name }}-macos.zip xcq

      - name: Ensure gh CLI
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            brew update
            brew install gh
          fi

      - name: Publish release via gh (idempotent)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="${{ github.ref_name }}"
          ASSET="dist/xcq-${TAG}-macos.zip"
          if ! gh release view "$TAG" >/dev/null 2>&1; then
            gh release create "$TAG" "$ASSET" --title "$TAG" --generate-notes
          else
            gh release upload "$TAG" "$ASSET" --clobber
          fi
