name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (release)
        run: swift build -c release

      - name: Package artifact
        run: |
          mkdir -p dist
          cp .build/release/xq dist/
          cd dist
          zip -r xq-${{ github.ref_name }}-macos.zip xq

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload binary asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/xq-${{ github.ref_name }}-macos.zip
          asset_name: xq-${{ github.ref_name }}-macos.zip
          asset_content_type: application/zip

