name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: macos-latest
    steps:
      - name: Checkout XcodeQuery
        uses: actions/checkout@v4

      - name: Prepare variables
        id: prep
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          # Prebuilt asset URL from the Release created by the release workflow
          ASSET_URL="https://github.com/alvarhansen/XcodeQuery/releases/download/${TAG}/xcq-${TAG}-macos.zip"
          echo "asset_url=$ASSET_URL" >> $GITHUB_OUTPUT
          # Extract version without leading 'v'
          VERSION_NO_V="${TAG#v}"
          echo "version=$VERSION_NO_V" >> $GITHUB_OUTPUT

      - name: Compute asset sha256
        id: sha
        run: |
          # Retry until the release asset is available to avoid race with the release job
          curl -fL --retry 30 --retry-delay 5 --retry-all-errors "${{ steps.prep.outputs.asset_url }}" -o xcq.zip
          SHASUM=$(shasum -a 256 xcq.zip | awk '{print $1}')
          echo "sha=$SHASUM" >> $GITHUB_OUTPUT

      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: alvarhansen/homebrew-xcodequery
          token: ${{ secrets.GITHUB_TOKEN }}
          path: tap

      - name: Update formula in tap (binary install)
        working-directory: tap
        run: |
          mkdir -p Formula
          cat > Formula/xcq.rb <<'RUBY'
class Xcq < Formula
  desc "Query and introspect Xcode projects from the CLI"
  homepage "https://github.com/alvarhansen/XcodeQuery"
  license "MIT"

  url "__ASSET_URL__"
  sha256 "__SHA__"
  version "__VERSION__"

  head "https://github.com/alvarhansen/XcodeQuery.git", branch: "main"

  def install
    if build.head?
      system "swift", "build", "-c", "release"
      bin.install ".build/release/xcq"
    else
      bin.install "xcq"
    end
  end

  test do
    system bin/"xcq", "--help"
  end
end
RUBY
          sed -i '' "s|__ASSET_URL__|${{ steps.prep.outputs.asset_url }}|g" Formula/xcq.rb
          sed -i '' "s|__SHA__|${{ steps.sha.outputs.sha }}|g" Formula/xcq.rb
          sed -i '' "s|__VERSION__|${{ steps.prep.outputs.version }}|g" Formula/xcq.rb
          git add Formula/xcq.rb
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update xcq to ${{ steps.prep.outputs.tag }}" || echo "No changes to commit"
          git push
